#!/usr/bin/python3
def raise_exception():
    integer = int(2)
    let = 'e'
    c = integer/let
    return c
